application:
  name: pchauhan-demo-project
  image: nginx
  namespace: demo-project-namespace
  port:
    containerPort: 80
  replicas: 1

service:
  name: demo-project-service
  type: LoadBalancer
  port: 80
