application:
  name: pchauhan-demo-project
  deployment: pchauhan-demo-project-deployment
  image: <aws ecr repository URI:tag>
  namespace: demo-project-namespace
  port:
    containerPort: 80
  replicas: 1

service:
  name: demo-project-service
  type: LoadBalancer
  port: 80
