namespace: pchauhan


configMap:
  app:
    name: ap-app-cm
  redis:
    name: ap-redis-cm

app:
################
## Deployment ##
################
  deployment: ap-app-deployment
  name: ap-app
  image: ap-laravel
  port: 
    containerPort: 5173
  replicas: 1

  volumeMountPath: 
  volumes:
    pv-app-name: app-pv
    pvc-app-name: app-pvc
    size: 5Gi
  volumeMounts:
    mountPath1:   
      path: /var/www
      name: pv-app-name
    mountPath2: 
      path: /usr/local/etc/php/conf.d/app.ini
      name: pvc-app-name
    


################
### Service ####
################
  service:
    name: ap-app-service
    port: 80
    targetPort: 80
    type: ClusterIP


nginx:
  deployment: ap-nginx-deployment
  image: nginx:alpine
  name: ap-nginx
  service:
    name: ap-nginx-service
    port: 80
    targetPort: 80
    type: LoadBalancer
  volumes:
    # - ./:/var/www
    # - ./dev/docker-compose/nginx:/etc/nginx/conf.d/

worker:
  image: ap-worker-local
  workingDir: /var/www
  volumes:
    # - ./:/var/www
    # - ./dev/docker-compose/php/app.ini:/usr/local/etc/php/conf.d/app.ini
  args:
    queueTimeout: 30
    queueTries: 2
    queues: default,indexing,notifications

mysql:
  service:
    name: mysql-service
    port: 3306
  image: mysql
  environment:
    MYSQL_DATABASE: {{ .Values.mysql.database }}
    MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
    MYSQL_PASSWORD: {{ .Values.mysql.password }}
    MYSQL_USER: {{ .Values.mysql.user }}
  volumes:
    # - ./dev/docker-compose/mysql:/docker-entrypoint-initdb.d

redis:
  image: redis
  port: 6379
  volumes:
    # - ./dev/docker-compose/redis/redis.conf:/usr/local/etc/redis/redis.conf
  healthcheck:
    test: [ "CMD", "redis-cli", "ping" ]

network:
  name: ap
