
persistence:
  webDirectory:
    pvName: web-directory-pv
    pvcName: web-directory-pvc
    size: 5Gi
    accessModes: ReadWriteMany
    storageClass: nfs-client


# imagePullSecrets:
#   name: regcred

configMap:
  app:
    name: ap-app-cm
  redis:
    name: ap-redis-cm
  env:
    name: ap-env-cm
  mysql:
    name: ap-mysql-cm
  nginx:
    name: ap-nginx-cm

app:
  deployment: ap-app-deployment
  name: laravel-ap-app
  image: 172.20.20.245:5000/app-laravel
  port: 
    containerPort: 5173
  replicas: 1
  volumeMountPath: 
  volumes:
    pvAppName: app-pv
    pvcAppName: app-pvc
  volumeMounts:
    mountPath1:   
      path: /var/www
      name: web-directory-pv
    mountPath2: 
      path: /usr/local/etc/php/conf.d/app.ini
      name: app-ini-cm
  service:
    name: ap-app-service
    port: 5173
    targetPort: 5173
    type: ClusterIP


nginx:
  deployment: ap-nginx-deployment
  image: nginx:alpine
  name: laravel-ap-nginx
  service:
    name: ap-nginx-service
    port: 80
    targetPort: 80
    type: LoadBalancer
  volumeMounts:
    mountPath1:   
      path: /var/www
      name: pv-nginx-name
    mountPath2: 
      path: /etc/nginx/conf.d/
      name: pvc-nginx-name
  volumes:
    pvNginxName: nginx-pv
    pvcNginxName: nginx-pvc


worker:
  deployment: ap-worker-deployment
  name: laravel-ap-worker
  image: 172.20.20.245:5000/ap-worker-local:v1.0.0
  replicas: 1
  workingDir: /var/www
  volumeMounts:
    mountPath1:   
      path: /var/www
      name: web-directory-pv
    mountPath2: 
      path: /usr/local/etc/php/conf.d/app.ini
      name: app-ini-cm
  volumes:
    pvWorkerName: worker-pv
    pvcWorkerName: worker-pvc
  args:
    queueTimeout: 30
    queueTries: 2
    queues: default,indexing,notifications
  service:
    name: laravel-ap-worker
    port: 9000
    targetPort: 9000
    type: ClusterIP

mysql:
  deployment: larvel-mysql-deployment
  name: laravel-mysql
  replicas: 1
  image: 172.20.20.245:5000/laravel-mysql:v1.0.0
  service:
    name: mysql-service
    port: 3306
    type: ClusterIP
  
redis:
  deployment: redis-deployment
  name: laravel-redis
  image: 172.20.20.245:5000/pchauhan-redis:v1.0.0
  replicas: 1
  service:
    name: laravel-redis-svc
    port: 6379
    type: ClusterIP
  volumeMounts:
    mountPath1:   
      path: /usr/local/etc/redis/redis.conf

  healthcheck:
    test: [ "CMD", "redis-cli", "ping" ]


