apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - image: ap-laravel
          name: ap-app
          ports:
            - containerPort: 5173
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www
              name: app-cm0
            - mountPath: /usr/local/etc/php/conf.d/app.ini
              name: app-cm1
              subPath: app.ini
          workingDir: /var/www/
      restartPolicy: Always
      volumes:
        - configMap:
            name: app-cm0
          name: app-cm0
        - configMap:
            items:
              - key: app.ini
                path: app.ini
            name: app-cm1
          name: app-cm1
