apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:alpine
          name: ap-nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www
              name: nginx-cm0
            - mountPath: /etc/nginx/conf.d
              name: nginx-cm1
      restartPolicy: Always
      volumes:
        - configMap:
            name: nginx-cm0
          name: nginx-cm0
        - configMap:
            name: nginx-cm1
          name: nginx-cm1
