apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: redis
    spec:
      containers:
        - args:
            - sh
            - -c
            - /redis/init.sh
          image: redis
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
          name: ap-redis
          ports:
            - containerPort: 6379
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /usr/local/etc/redis/redis.conf
              name: redis-cm0
              subPath: redis.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: redis.conf
                path: redis.conf
            name: redis-cm0
          name: redis-cm0
