apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: worker-local
  name: worker-local
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker-local
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: worker-local
    spec:
      containers:
        - image: 172.20.20.245:5000/ap-worker-local:v1.0.0
          name: ap-worker-local
          volumeMounts:
            - mountPath: /var/www
              name: worker-local-cm0
            - mountPath: /usr/local/etc/php/conf.d/app.ini
              name: worker-local-cm1
              subPath: app.ini
          workingDir: /var/www/
      restartPolicy: Always
      volumes:
        - configMap:
            name: worker-local-cm0
          name: worker-local-cm0
        - configMap:
            items:
              - key: app.ini
                path: app.ini
            name: worker-local-cm1
          name: worker-local-cm1
