apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.containerName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: {{ .Values.app.containerName }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.ports[0].targetPort }}
        volumeMounts:
        - mountPath: {{ .Values.app.volumeMountPath }}
          name: app-volume
        - mountPath: /usr/local/etc/php/conf.d/app.ini
          subPath: app.ini
          name: config-volume
      volumes:
      - name: app-volume
        persistentVolumeClaim:
          claimName: app-pvc
      - name: config-volume
        configMap:
          name: app-config

