apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.deployment }}
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port.containerPort }}
        volumeMounts:
        - mountPath: {{ .Values.app.volumeMountPath }}
          name: {{.Values.persistence.pv-app-name }}
        - mountPath: /usr/local/etc/php/conf.d/app.ini
          # subPath: app.ini
          name: config-volume
      volumes:
      - name: {{.Values.persistence.pv-app-name }}
        persistentVolumeClaim:
          claimName: {{.Values.persistence.pvc-app-name }}
      - name: config-volume
        configMap:
          name: app-config

