apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.deployment }}
  namespace: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port.containerPort }}
        volumeMounts:
        - mountPath: {{ .Values.app.volumeMounts.mountPath1.path }}
          name: {{.Values.app.volumeMounts.mountPath1.name }}
        - mountPath: {{ .Values.app.volumeMounts.mountPath2.path }}
          name: {{.Values.app.volumeMounts.mountPath2.name}}
      - name: file-copier
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            cp -r ../../* {{ .Values.app.volumeMounts.mountPath1.path }};
            sleep 3600; # Keeps the container alive
        volumeMounts:
        - name: {{.Values.app.volumeMounts.mountPath1.name}}
          mountPath: {{ .Values.app.volumeMounts.mountPath1.path }}
      volumes:
      - name: {{.Values.app.volumeMounts.mountPath1.name}}
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{.Values.persistence.webDirectory.pvcName }}"
      - name: {{.Values.app.volumeMounts.mountPath2.name }}
        configMap:
          name: "{{ .Release.Name }}-{{.Values.configMap.app.name}}"

