apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: {{ .Values.app.service.name }}
      port: {{ .Values.app.port.containerPort }}
      targetPort: {{ .Values.app.port.containerPort }}
  selector:
    app: {{ .Values.app.name }}