apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{ .Release.Name }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: {{ .Values.app.service.name }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  selector:
    app: {{ .Values.app.name }}