apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.app.serviceName }}
      port: {{ .Values.app.port.containerPort }}
      targetPort: {{ .Values.app.port.containerPort }}
  selector:
    app: {{ .Values.app.name }}