apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.containerName }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.app.ports[0].name }}
      port: {{ .Values.app.ports[0].port }}
      targetPort: {{ .Values.app.ports[0].targetPort }}
  selector:
    app: {{ .Release.Name }}-app
