apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.deployment }}
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image }}
        ports:
        - containerPort: {{ .Values.app.port.containerPort }}
        volumeMounts:
        - mountPath: {{ .Values.app.volumeMounts.mountPath1 }}
          name: {{.Values.app.volumes.pv-app-name }}
        - mountPath: {{ .Values.app.volumeMounts.mountPath2 }}
          name: config-volume
      volumes:
      - name: {{.Values.app.volumes.pv-app-name }}
        persistentVolumeClaim:
          claimName: {{.Values.app.volumes.pvc-app-name }}
      - name: {{.Values.configMap.app.name }}
        configMap:
          name: "{{ .Release.Name }}-{{.Values.configMap.app.name}}"

