apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.deployment }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Values.mysql.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  replicas: {{ .Values.mysql.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: {{ .Values.mysql.image }}
          command: ["mysqld"]
          args: ['--sql_mode=""']
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
          env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{.Values.configMap.env.name}}
                key: DB_DATABASE
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{.Values.configMap.env.name}}
                key: DB_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{.Values.configMap.env.name}}
                key: DB_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: {{.Values.configMap.env.name}}
                key: DB_USERNAME
          volumeMounts:
          - name: mysql-init-scripts
            mountPath: /docker-entrypoint-initdb.d
            subPath: init_db.sql
          - name: mysql-init-scripts
            mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
            subPath: mysqld.cnf
      volumes:
      - name: mysql-init-scripts
        configMap:
          name: "{{ .Release.Name }}-{{.Values.configMap.mysql.name}}"
