apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.deployment }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Values.mysql.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  replicas: {{ .Values.mysql.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: {{ .Values.mysql.image }}
          # command: ["mysqld"]
          # args: ["--sql_mode="]
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
          env:
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: "{{ .Release.Name }}-{{.Values.configMap.env.name}}"
                key: DB_DATABASE
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: "{{ .Release.Name }}-{{.Values.configMap.env.name}}"
                key: DB_PASSWORD
          # - name: MYSQL_PASSWORD
          #   valueFrom:
          #     configMapKeyRef:
          #       name: "{{ .Release.Name }}-{{.Values.configMap.env.name}}"
          #       key: DB_PASSWORD
          # - name: MYSQL_USER
          #   valueFrom:
          #     configMapKeyRef:
          #       name: "{{ .Release.Name }}-{{.Values.configMap.env.name}}"
          #       key: DB_USERNAME
          volumeMounts:
          - name: mysql-init-scripts
            mountPath: /docker-entrypoint-initdb.d
          - mountPath: {{ .Values.mysql.volumeMounts.mountPath1.path }}
            name: {{.Values.mysql.volumeMounts.mountPath1.name }}
      volumes:
      - name: mysql-init-scripts
        configMap:
          name: "{{ .Release.Name }}-{{.Values.configMap.mysql.name}}"
      - name: {{.Values.mysql.volumeMounts.mountPath1.name}}
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{.Values.persistence.mysql.pvcName }}"
