apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
  type: ClusterIP
