apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.nginx.service.name }}"
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
spec:
  selector:
    app: {{ .Values.nginx.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
  type: {{ .Values.nginx.service.type }}
