apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-{{ .Values.nginx.deployment }}"
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Values.nginx.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  replicas: {{ .Values.nginx.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
        - name: {{ .Values.nginx.name }}
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: {{ .Values.nginx.service.port }}
          volumeMounts:
          - mountPath: {{ .Values.nginx.volumeMounts.mountPath1.path }}
            name: {{.Values.nginx.volumes.pvNginxName }}
          - mountPath: {{ .Values.nginx.volumeMounts.mountPath2.path }}
            name: {{.Values.configMap.nginx.name}}
      volumes:
      - name: {{.Values.nginx.volumes.pvNginxName }}
        persistentVolumeClaim:
          claimName: {{.Values.persistence.webDirectory.pvcName }}
      - name: {{.Values.configMap.nginx.name}}
        configMap:
          name: "{{ .Release.Name }}-{{.Values.configMap.nginx.name}}"
