apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
spec:
  selector:
    app: {{ .Values.redis.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
  type: {{ .Values.redis.service.type }}
