apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.deployment }}
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  replicas: {{ .Values.redis.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.service.port }}
          volumeMounts:
          - mountPath: {{ .Values.redis.volumeMounts.mountPath1.path }}
            name: {{.Values.configMap.redis.name}}
      volumes:
      - name: {{.Values.configMap.redis.name}}
        configMap:
          name: "{{ .Release.Name }}-{{.Values.configMap.redis.name}}"
