apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 1234 # Example port
      targetPort: 1234
  type: ClusterIP
