apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.deployment }}
  namespace: {{ .Release.Name }}
  labels:
    prod: {{ .Values.worker.name }}
spec:
  selector:
    matchLabels:
      prod: {{ .Values.worker.name }}
  replicas: {{ .Values.worker.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        prod: {{ .Values.worker.name }}
    spec:
      containers:
        - name: {{ .Values.worker.name }}
          image: {{ .Values.worker.image }}
          env:
          - name: QUEUE_TIMEOUT
            value: "{{ .Values.worker.env.QUEUE_TIMEOUT }}"
          - name: QUEUE_TRIES
            value: "{{ .Values.worker.env.QUEUE_TRIES }}"
          - name: QUEUES
            value: "{{ .Values.worker.env.QUEUES }}"
          command:
          - sh
          - -c
          - |
            cd {{ .Values.worker.volumeMounts.mountPath1.path }}
            composer install --no-dev --optimize-autoloader
            composer dump-autoload --optimize
            chmod 777 /var/www/storage/ -R
            php artisan queue:work redis --queue=${QUEUES} --timeout=${QUEUE_TIMEOUT} --tries=${QUEUE_TRIES} 
          ports:
            - containerPort: {{ .Values.worker.service.port }}
          volumeMounts:
          - mountPath: {{ .Values.worker.volumeMounts.mountPath1.path }}
            name: {{.Values.worker.volumeMounts.mountPath1.name }}
          - mountPath: {{ .Values.worker.volumeMounts.mountPath2.path }}
            name: {{.Values.worker.volumeMounts.mountPath2.name }}
      volumes:
      - name: {{.Values.worker.volumeMounts.mountPath1.name}}
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-{{.Values.persistence.webDirectory.pvcName }}"
      - name: {{.Values.worker.volumeMounts.mountPath2.name }}
        configMap:
          name: "{{ .Release.Name }}-{{.Values.configMap.app.name}}"
