apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.application.deployment | quote } }
  namespace: { { .Values.application.namespace } }
  labels:
    app: { { .Values.application.name | quote } }
spec:
  selector:
    matchLabels:
      app: { { .Values.application.name | quote } }
  replicas: { { .Values.application.replicas } }
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: { { .Values.application.name | quote } }
    spec:
      containers:
        - name: { { .Values.application.name | quote } }
          image: { { .Values.application.image } }
          ports:
            - containerPort: { { .Values.application.port.containerPort } }
