apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{.Values.persistence.webDirectory.pvcName }}"
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
spec:
  accessModes: {{.Values.persistence.webDirectory.accessModes }}
  resources:
    requests:
      storage: {{.Values.persistence.webDirectory.size }}
  storageClassName: "{{ .Values.persistence.webDirectory.storageClass }}"
