# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: "{{ .Release.Name }}-{{.Values.persistence.web-directory.pv-name }}"
#   namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
# spec:
#   capacity:
#     storage: {{.Values.persistence.web-directory.size }}
#   accessModes:
#     - {{.Values.persistence.web-directory.accessModes }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{.Values.persistence.web-directory.pvs-name }}"
  namespace: "{{ .Release.Name }}-{{ .Values.namespace }}"
spec:
  accessModes:
    - {{.Values.persistence.web-directory.accessModes }}
  resources:
    requests:
      storage: {{.Values.persistence.web-directory.size }}
  storageClassName: "{{ .Values.persistence.web-directory.storageClass }}"
