apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-{{.Values.app.volumes.pv-app-name }}"
  namespace: "{{ .Values.namespace }}-{{ .Values.namespace }}"
spec:
  capacity:
    storage: {{.Values.app.volumes.size }}
  accessModes:
    - {{.Values.app.volumes.accessModes }}
  # hostPath:
  #   path: "{{ .Values.volumes.hostPath }}/app"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{.Values.app.volumes.pv-app-name }}"
  namespace: "{{ .Values.namespace }}-{{ .Values.namespace }}"
spec:
  accessModes:
    - {{.Values.app.volumes.accessModes }}
  resources:
    requests:
      storage: {{.Values.app.volumes.size }}
