# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: "{{ .Release.Name }}-{{.Values.persistence.webDirectory.pvName }}"
#   namespace: {{ .Release.Name }}
# spec:
#   capacity:
#     storage: {{.Values.persistence.webDirectory.size }}
#   accessModes:
#     - {{.Values.persistence.webDirectory.accessModes }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{.Values.persistence.webDirectory.pvcName }}"
  namespace: {{ .Release.Name }}
spec:
  accessModes: 
  - {{.Values.persistence.webDirectory.accessModes }}
  resources:
    requests:
      storage: {{.Values.persistence.webDirectory.size }}
  storageClassName: "{{ .Values.persistence.webDirectory.storageClass }}"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-{{.Values.persistence.webDirectory.pvcName }}"
  namespace: {{ .Release.Name }}
spec:
  accessModes: 
  - {{.Values.persistence.webDirectory.accessModes }}
  resources:
    requests:
      storage: {{.Values.persistence.webDirectory.size }}
  storageClassName: "{{ .Values.persistence.webDirectory.storageClass }}"
