apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{persistence.}}-{{}}"
  namespace: "{{ .Values.namespace }}-{{ .Values.namespace }}"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{ .Values.volumes.hostPath }}/app"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: "{{ .Values.namespace }}-{{ .Values.namespace }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
