apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.application.image }}
spec:
  selector:
    app: {{ .Values.application.name }}
  type: {{ .Values.service.type }}
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: {{ .Values.service.name.service.Name }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort:
      # If you set the `spec.type` field to `NodePort` and you want a specific port number,
      # you can specify a value in the `spec.ports[*].nodePort` field.
